[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
new_swap = "BZfoyQyAiyo6EVAEnrxBWPgjruRo8Zi3xXduRcq1HbLo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
